import type { FoodItem } from './types';

export const foodLibrary: FoodItem[] = [
  { id: '1', name: 'Roti (Chapati)', serving: '1 medium', category: 'veg', calories: 104, protein: 3, carbs: 22, fat: 0.5 },
  { id: '2', name: 'Dal Tadka', serving: '1 cup', category: 'veg', calories: 150, protein: 8, carbs: 20, fat: 4 },
  { id: '3', name: 'Paneer Butter Masala', serving: '1 cup', category: 'veg', calories: 350, protein: 18, carbs: 12, fat: 25 },
  { id: '4', name: 'Steamed Rice', serving: '1 cup', category: 'veg', calories: 205, protein: 4, carbs: 45, fat: 0.5 },
  { id: '5', name: 'Chicken Curry', serving: '1 cup', category: 'non-veg', calories: 320, protein: 25, carbs: 8, fat: 20 },
  { id: '6', name: 'Aloo Gobi', serving: '1 cup', category: 'veg', calories: 130, protein: 4, carbs: 18, fat: 5 },
  { id: '7', name: 'Mixed Vegetable Salad', serving: '1 bowl', category: 'veg', calories: 80, protein: 2, carbs: 10, fat: 3 },
  { id: '8', name: 'Samosa', serving: '1 piece', category: 'veg', calories: 262, protein: 4, carbs: 32, fat: 14 },
  { id: '9', name: 'Tandoori Chicken', serving: '1 leg piece', category: 'non-veg', calories: 220, protein: 26, carbs: 2, fat: 12 },
  { id: '10', name: 'Boiled Egg', serving: '1 large', category: 'egg', calories: 78, protein: 6, carbs: 0.6, fat: 5 },
  { id: '11', name: 'Masala Dosa', serving: '1 piece', category: 'veg', calories: 380, protein: 8, carbs: 65, fat: 10 },
  { id: '12', name: 'Idli', serving: '2 pieces', category: 'veg', calories: 140, protein: 4, carbs: 30, fat: 1 },
  { id: '13', name: 'Plain Yogurt (Dahi)', serving: '1 cup', category: 'veg', calories: 150, protein: 12, carbs: 16, fat: 4 },
  { id: '14', name: 'Fish Fry', serving: '1 fillet', category: 'non-veg', calories: 250, protein: 22, carbs: 5, fat: 15 },
  { id: '15', name: 'Palak Paneer', serving: '1 cup', category: 'veg', calories: 290, protein: 16, carbs: 10, fat: 22 },
  { id: '16', name: 'Chole (Chickpea Curry)', serving: '1 cup', category: 'veg', calories: 280, protein: 12, carbs: 45, fat: 6 },
  { id: '17', name: 'Biryani (Chicken)', serving: '1 plate', category: 'non-veg', calories: 450, protein: 24, carbs: 55, fat: 15 },
  { id: '18', name: 'Rajma (Kidney Bean Curry)', serving: '1 cup', category: 'veg', calories: 330, protein: 15, carbs: 58, fat: 4 },
  { id: '19', name: 'Gulab Jamun', serving: '2 pieces', category: 'veg', calories: 300, protein: 4, carbs: 40, fat: 14 },
  { id: '20', name: 'Jalebi', serving: '2 pieces', category: 'veg', calories: 250, protein: 2, carbs: 50, fat: 5 },
  { id: '21', name: 'Naan Bread', serving: '1 piece', category: 'veg', calories: 310, protein: 9, carbs: 56, fat: 5 },
  { id: '22', name: 'Butter Chicken', serving: '1 cup', category: 'non-veg', calories: 490, protein: 30, carbs: 12, fat: 35 },
  { id: '23', name: 'Bhindi Masala (Okra)', serving: '1 cup', category: 'veg', calories: 140, protein: 3, carbs: 15, fat: 8 },
  { id: '24', name: 'Mutton Rogan Josh', serving: '1 cup', category: 'non-veg', calories: 400, protein: 28, carbs: 7, fat: 28 },
  { id: '25', name: 'Lassi (Sweet)', serving: '1 glass', category: 'veg', calories: 220, protein: 6, carbs: 35, fat: 6 },
  { id: '26', name: 'Mango Lassi', serving: '1 glass', category: 'veg', calories: 250, protein: 6, carbs: 45, fat: 5 },
  { id: '27', name: 'Poha', serving: '1 plate', category: 'veg', calories: 270, protein: 5, carbs: 50, fat: 5 },
  { id: '28', name: 'Upma', serving: '1 cup', category: 'veg', calories: 250, protein: 6, carbs: 40, fat: 8 },
  { id: '29', name: 'Gajar Ka Halwa', serving: '1 bowl', category: 'veg', calories: 380, protein: 6, carbs: 50, fat: 18 },
  { id: '30', name: 'Rasgulla', serving: '2 pieces', category: 'veg', calories: 200, protein: 4, carbs: 45, fat: 1 },
  { id: '31', name: 'Vada Pav', serving: '1 piece', category: 'veg', calories: 300, protein: 6, carbs: 48, fat: 10 },
  { id: '32', name: 'Pav Bhaji', serving: '1 plate', category: 'veg', calories: 400, protein: 10, carbs: 60, fat: 15 },
  { id: '33', name: 'Dhokla', serving: '2 pieces', category: 'veg', calories: 150, protein: 6, carbs: 25, fat: 3 },
  { id: '34', name: 'Khandvi', serving: '4 pieces', category: 'veg', calories: 180, protein: 7, carbs: 15, fat: 10 },
  { id: '35', name: 'Baingan Bharta', serving: '1 cup', category: 'veg', calories: 110, protein: 3, carbs: 15, fat: 5 },
  { id: '36', name: 'Dal Makhani', serving: '1 cup', category: 'veg', calories: 380, protein: 14, carbs: 35, fat: 20 },
  { id: '37', name: 'Malai Kofta', serving: '1 cup', category: 'veg', calories: 400, protein: 10, carbs: 15, fat: 35 },
  { id: '38', name: 'Shahi Paneer', serving: '1 cup', category: 'veg', calories: 370, protein: 18, carbs: 10, fat: 30 },
  { id: '39', name: 'Kadhi Pakora', serving: '1 cup', category: 'veg', calories: 250, protein: 10, carbs: 25, fat: 12 },
  { id: '40', name: 'Chicken Tikka Masala', serving: '1 cup', category: 'non-veg', calories: 370, protein: 28, carbs: 10, fat: 24 },
  { id: '41', name: 'Egg Bhurji', serving: '1 cup (2 eggs)', category: 'egg', calories: 220, protein: 14, carbs: 5, fat: 16 },
  { id: '42', name: 'Omelette (2 eggs)', serving: '1 piece', category: 'egg', calories: 180, protein: 13, carbs: 2, fat: 14 },
  { id: '43', name: 'Prawn Curry', serving: '1 cup', category: 'non-veg', calories: 280, protein: 20, carbs: 6, fat: 18 },
  { id: '44', name: 'Aloo Paratha', serving: '1 piece', category: 'veg', calories: 290, protein: 6, carbs: 45, fat: 10 },
  { id: '45', name: 'Gobi Paratha', serving: '1 piece', category: 'veg', calories: 250, protein: 7, carbs: 40, fat: 8 },
  { id: '46', name: 'Paneer Paratha', serving: '1 piece', category: 'veg', calories: 350, protein: 15, carbs: 40, fat: 15 },
  { id: '47', name: 'Poori', serving: '2 pieces', category: 'veg', calories: 250, protein: 4, carbs: 30, fat: 13 },
  { id: '48', name: 'Bhatura', serving: '1 piece', category: 'veg', calories: 300, protein: 6, carbs: 45, fat: 11 },
  { id: '49', name: 'Raita (Boondi)', serving: '1 cup', category: 'veg', calories: 120, protein: 6, carbs: 10, fat: 6 },
  { id: '50', name: 'Cucumber Raita', serving: '1 cup', category: 'veg', calories: 80, protein: 5, carbs: 8, fat: 3 },
  { id: '51', name: 'Vegetable Korma', serving: '1 cup', category: 'veg', calories: 250, protein: 6, carbs: 18, fat: 18 },
  { id: '52', name: 'Mushroom Masala', serving: '1 cup', category: 'veg', calories: 180, protein: 8, carbs: 12, fat: 12 },
  { id: '53', name: 'Lemon Rice', serving: '1 cup', category: 'veg', calories: 300, protein: 5, carbs: 55, fat: 7 },
  { id: '54', 'name': 'Tamarind Rice', 'serving': '1 cup', 'category': 'veg', 'calories': 320, 'protein': 6, 'carbs': 60, 'fat': 8 },
  { id: '55', name: 'Coconut Chutney', serving: '2 tbsp', category: 'veg', calories: 100, protein: 1, carbs: 3, fat: 10 },
  { id: '56', name: 'Mint Chutney', serving: '2 tbsp', category: 'veg', calories: 20, protein: 1, carbs: 4, fat: 0 },
  { id: '57', name: 'Sambar', serving: '1 cup', category: 'veg', calories: 120, protein: 6, carbs: 20, fat: 2 },
  { id: '58', name: 'Rasam', serving: '1 cup', category: 'veg', calories: 50, protein: 2, carbs: 10, fat: 1 },
  { id: '59', name: 'Papadum (Roasted)', serving: '2 pieces', category: 'veg', calories: 80, protein: 4, carbs: 15, fat: 0.5 },
  { id: '60', name: 'Pickle (Achar)', serving: '1 tbsp', category: 'veg', calories: 40, protein: 0.2, carbs: 2, fat: 4 },
  { id: '61', name: 'Kheer (Rice Pudding)', serving: '1 bowl', category: 'veg', calories: 300, protein: 8, carbs: 45, fat: 10 },
  { id: '62', name: 'Shrikhand', serving: '1 bowl', category: 'veg', calories: 280, protein: 8, carbs: 40, fat: 10 },
  { id: '63', name: 'Masala Chai', serving: '1 cup', category: 'veg', calories: 80, protein: 2, carbs: 10, fat: 3 },
  { id: '64', name: 'Filter Coffee', serving: '1 cup', category: 'veg', calories: 100, protein: 2, carbs: 12, fat: 4 },
  { id: '65', name: 'Keema Matar', serving: '1 cup', category: 'non-veg', calories: 350, protein: 25, carbs: 10, fat: 22 },
  { id: '66', name: 'Seekh Kebab', serving: '2 pieces', category: 'non-veg', calories: 280, protein: 20, carbs: 3, fat: 20 },
  { id: '67', name: 'Haleem', serving: '1 bowl', category: 'non-veg', calories: 450, protein: 30, carbs: 35, fat: 20 },
  { id: '68', name: 'Chicken 65', serving: '1 plate', category: 'non-veg', calories: 360, protein: 25, carbs: 15, fat: 20 },
  { id: '69', name: 'Pani Puri', serving: '6 pieces', category: 'veg', calories: 200, protein: 4, carbs: 35, fat: 5 },
  { id: '70', name: 'Bhel Puri', serving: '1 plate', category: 'veg', calories: 280, protein: 6, carbs: 50, fat: 7 },
  { id: '71', name: 'Sev Puri', serving: '1 plate', category: 'veg', calories: 320, protein: 7, carbs: 45, fat: 13 },
  { id: '72', name: 'Dahi Vada', serving: '2 pieces', category: 'veg', calories: 250, protein: 8, carbs: 30, fat: 10 },
  { id: '73', name: 'Misal Pav', serving: '1 plate', category: 'veg', calories: 350, protein: 12, carbs: 45, fat: 12 },
  { id: '74', name: 'Sabudana Khichdi', serving: '1 plate', category: 'veg', calories: 480, protein: 5, carbs: 80, fat: 15 },
  { id: '75', name: 'Thepla', serving: '2 pieces', category: 'veg', calories: 220, protein: 6, carbs: 30, fat: 9 },
  { id: '76', name: 'Sarson ka Saag', serving: '1 cup', category: 'veg', calories: 150, protein: 6, carbs: 12, fat: 9 },
  { id: '77', name: 'Makki di Roti', serving: '1 piece', category: 'veg', calories: 180, protein: 4, carbs: 30, fat: 5 },
  { id: '78', name: 'Litti Chokha', serving: '1 plate', category: 'veg', calories: 380, protein: 10, carbs: 65, fat: 8 },
  { id: '79', name: 'Pesarattu', serving: '1 piece', category: 'veg', calories: 200, protein: 12, carbs: 30, fat: 4 },
  { id: '80', name: 'Avial', serving: '1 cup', category: 'veg', calories: 180, protein: 5, carbs: 15, fat: 12 },
  { id: '81', name: 'Kuzhi Paniyaram', serving: '4 pieces', category: 'veg', calories: 200, protein: 6, carbs: 35, fat: 4 },
];
